services:

  mariadb:
    container_name: mariadb
    image: mariadb.image:last
    build: requirements/mariadb/
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx.image:last
    build: requirements/nginx/
    volumes:
      - wordpress_vol:/var/www/inception.site
    ports:
      - 443:443
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress.image:last
    build: requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/inception.site
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rdupeux/data/mariadb
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rdupeux/data/wordpress
