services:

  mariadb:
    container_name: mariadb
    image: mariadb.image:last
    build: requirements/mariadb/
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx.image:last
    build: requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wordpress_vol:/var/www/inception.site
    restart: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress.image:last
    build: requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/inception.site
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:

volumes:
  db_vol:
  wordpress_vol:
