FROM debian:bookworm

WORKDIR /setup

RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install mariadb-server

RUN mkdir -p /var/lib/mysql \
&& chown -R mysql:mysql /var/lib/mysql \
&& chmod 777 /var/lib/mysql

COPY tools/mariadb-setup.sh .
RUN chmod +x mariadb-setup.sh
COPY tools/mariadb.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN chown -R mysql: /var/lib/mysql

COPY tools/db.dump wordpress.sql

EXPOSE 3306

CMD ["./mariadb-setup.sh"]
