FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install nginx openssl

#COPY tools/sites-availables.conf etc/nginx/sites-available/inception_site_conf
COPY tools/nginx.conf etc/nginx/conf.d/

RUN mkdir /etc/nginx/ssl/
RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
       -out /etc/nginx/ssl/certif_inception.crt \
       -keyout /etc/nginx/ssl/inception.key \
       -subj "/C=FR/ST=Paris/L=Paris/O=42 School/OU=42/CN=rdupeux/"

EXPOSE 443

RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log

CMD ["nginx", "-g", "daemon off;"]
